
import { config } from 'dotenv';
config({ path: '.env.local' });
import { db } from '@/lib/db';
import { generatedDrafts, users, pillars } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';

async function main() {
    console.log('🧪 Verifying Quick Post Backend Fix...');

    try {
        // 1. Get a user and a pillar
        const user = await db.query.users.findFirst();
        if (!user) throw new Error('No user found');
        const pillar = await db.query.pillars.findFirst({ where: eq(pillars.userId, user.id) });
        if (!pillar) throw new Error('No pillar found');

        console.log(`👤 Using User: ${user.id}`);
        console.log(`🏛️ Using Pillar: ${pillar.id}`);

        // 2. Simulate Quick Post Payload (matches frontend)
        const payload = {
            userId: user.id,
            pillarId: pillar.id,
            topicId: null, // Quick Posts have no topic
            fullText: "This is a test quick post generated by verification script.",
            userPerspective: "My original idea for this post.", // This was the missing field
            variantLetter: "A",
            characterCount: 100,
            status: "draft",
            metadata: {
                source: "quick_post",
                style: "narrative"
            }
        };

        // 3. Attempt Insert directly (simulating what the API does internally)
        // Note: We are testing the DB constraint here, effectively.
        // The API route logic adds the fallback, but the DB must accept this payload.

        console.log('📝 Attempting to insert Quick Post draft...');
        const [draft] = await db.insert(generatedDrafts).values(payload as any).returning();

        console.log('✅ Draft Inserted Successfully!');
        console.log('🆔 Draft ID:', draft.id);
        console.log('👁️ User Perspective:', draft.userPerspective);
        console.log('🔗 Topic ID:', draft.topicId);

        if (draft.userPerspective !== payload.userPerspective) {
            console.error('❌ User Perspective mismatch!');
        }
        if (draft.topicId !== null) {
            console.error('❌ Topic ID should be null!');
        }

        // Cleanup
        await db.delete(generatedDrafts).where(eq(generatedDrafts.id, draft.id));
        console.log('🧹 Cleanup complete.');

    } catch (e: any) {
        console.error('❌ Verification FAILED:', e);
    }
    process.exit(0);
}

main().catch(console.error);
